"""Anchor FastAPI app - HTTP API for the caregiver chat + doctor brief.

Endpoints:
    POST /chat            - one caregiver message -> memory-grounded answer
    GET  /brief           - generate a one-page doctor-visit brief from memory
    GET  /health          - liveness probe

Run:  uvicorn agent.main:app --reload
"""
from __future__ import annotations

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from .catch import catch
from .loop import run_loop
from memory.client import get_bank_id, recall

app = FastAPI(title="Anchor - Caregiver Memory Agent", version="0.1.0")


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000,
                         description="Caregiver message")
    bank_id: str | None = None


class ChatResponse(BaseModel):
    answer: str
    risk: bool = False
    risk_reason: str | None = None


class BriefResponse(BaseModel):
    brief: str


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    bank_id = req.bank_id or get_bank_id()

    # Run the catch engine for safety-sensitive wording.
    try:
        caught = catch(bank_id, req.message)
    except Exception:  # noqa: BLE001
        caught = {"risk": False, "reason": None, "evidence": []}

    result = run_loop(req.message, bank_id)

    # If the catch engine found a risk the loop didn't, merge it.
    if caught.get("risk") and not result.get("risk_reason"):
        result["risk"] = True
        result["risk_reason"] = caught.get("reason")

    return ChatResponse(
        answer=result["answer"],
        risk=result["risk"],
        risk_reason=result["risk_reason"],
    )


@app.get("/brief", response_model=BriefResponse)
def brief(bank_id: str | None = None) -> BriefResponse:
    """Generate a doctor-visit brief from the family's memory."""
    bank_id = bank_id or get_bank_id()
    try:
        meds = recall(bank_id, "current medications and doses", budget="high")
        conditions = recall(bank_id, "diagnoses and conditions", budget="high")
        recent = recall(bank_id, "recent symptoms and observations this week", budget="high")
        providers = recall(bank_id, "doctors and providers and phone numbers", budget="mid")
    except Exception as exc:  # noqa: BLE001 - surface a clean 503, not a raw 500
        raise HTTPException(status_code=503, detail=f"Memory unavailable: {exc}")

    lines = ["# Doctor Visit Brief", ""]
    lines.append("## Current Medications")
    lines += [f"- {m}" for m in meds] or ["- (none recorded)"]
    lines.append("")
    lines.append("## Known Conditions")
    lines += [f"- {c}" for c in conditions] or ["- (none recorded)"]
    lines.append("")
    lines.append("## Recent Observations")
    lines += [f"- {r}" for r in recent] or ["- (none recorded)"]
    lines.append("")
    lines.append("## Care Team")
    lines += [f"- {p}" for p in providers] or ["- (none recorded)"]
    lines.append("")
    lines.append("_Generated by Anchor from the family's persistent Hindsight memory._")
    return BriefResponse(brief="\n".join(lines))
